### PR TITLE
Update Quarkus lab documentation

### PR DESCRIPTION
**Pull request by akouao**

### CODE REVIEW

**Comment by browningjp** [comment]
Looks good - just one thing I thought of...

putting in an email address of username@no-reply.com - no-reply.com is a valid domain name that someone maybe owns so we may be pointing a load of junk mail towards them. Does it work using @example.com instead? example.com is reserved for this kind of thing - see here https://en.wikipedia.org/wiki/Example.com

**Comment by akouao** [comment]
Good shout!

**Comment by browningjp** [comment]
Don't need to close pull request and create a new one, just push a change to your master branch and it will update! :)

**Comment by akouao** [comment]
Whoops. Thought it only considered the state at the time of creating the PR!!

**Pull request closed without merging**
